INCLUDE "framework.4th"
\ Test ADD-INPUT-LINE forms: direct string, counted-addr, addr u

: TEST-ADDINPUT-DIRECT
  S" HELLO" ADD-INPUT-LINE
  CREATE B 16 ALLOT
  B 10 READ-LINE DROP
  B C@ 72 = ASSERT-TRUE
  B 1 + C@ 69 = ASSERT-TRUE
  B 2 + C@ 76 = ASSERT-TRUE
  B 3 + C@ 76 = ASSERT-TRUE
  B 4 + C@ 79 = ASSERT-TRUE
;
S" ADD-INPUT-LINE-DIRECT" TEST-CASE TEST-ADDINPUT-DIRECT

: TEST-ADDINPUT-COUNTED
  CREATE C 16 ALLOT
  5 C !
  72 C 1 + C! 69 C 2 + C! 76 C 3 + C! 76 C 4 + C! 79 C 5 + C!
  C ADD-INPUT-LINE
  CREATE B 16 ALLOT
  B 10 READ-LINE DROP
  B C@ 72 = ASSERT-TRUE
  B 1 + C@ 69 = ASSERT-TRUE
  B 2 + C@ 76 = ASSERT-TRUE
  B 3 + C@ 76 = ASSERT-TRUE
  B 4 + C@ 79 = ASSERT-TRUE
;
S" ADD-INPUT-LINE-COUNTED" TEST-CASE TEST-ADDINPUT-COUNTED

: TEST-ADDINPUT-ADDRLEN
  CREATE D 16 ALLOT
  72 D C! 69 D 1 + C! 76 D 2 + C! 76 D 3 + C! 79 D 4 + C!
  D 5 ADD-INPUT-LINE
  CREATE B 16 ALLOT
  B 10 READ-LINE DROP
  B C@ 72 = ASSERT-TRUE
  B 1 + C@ 69 = ASSERT-TRUE
  B 2 + C@ 76 = ASSERT-TRUE
  B 3 + C@ 76 = ASSERT-TRUE
  B 4 + C@ 79 = ASSERT-TRUE
;
S" ADD-INPUT-LINE-ADDRLEN" TEST-CASE TEST-ADDINPUT-ADDRLEN
