\ Arithmetic tests
INCLUDE "framework.4th"
: TEST-ADD 2 3 + 5 = ASSERT-TRUE ;
S" ADD" TEST-CASE TEST-ADD

: TEST-MUL 6 7 * 42 = ASSERT-TRUE ;
S" MUL" TEST-CASE TEST-MUL

: TEST-DIV 20 4 / 5 = ASSERT-TRUE ;
S" DIV" TEST-CASE TEST-DIV
